% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\title{Q4}
\author{Yuqi Gu}
\date{7/13/2024}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Q4},
  pdfauthor={Yuqi Gu},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
usepackage{multirow}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\begin{document}
\maketitle

\hypertarget{a}{%
\subsubsection{(a)}\label{a}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{but.dat }\OtherTok{\textless{}{-}} \FunctionTok{read.table}\NormalTok{(}\StringTok{"\textasciitilde{}/Desktop/STAT 332/Assignments/A3/walk\_button.txt"}\NormalTok{)}
\FunctionTok{names}\NormalTok{(but.dat) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"pushes\_num"}\NormalTok{, }\StringTok{"wait\_time"}\NormalTok{)}
\NormalTok{but.dat}\SpecialCharTok{$}\NormalTok{pushes\_num }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(but.dat}\SpecialCharTok{$}\NormalTok{pushes\_num)}
\NormalTok{but.aov }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(wait\_time }\SpecialCharTok{\textasciitilde{}}\NormalTok{ pushes\_num, }\AttributeTok{data =}\NormalTok{ but.dat)}
\FunctionTok{summary}\NormalTok{(but.aov)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             Df  Sum Sq  Mean Sq F value Pr(>F)
## pushes_num   3 0.00805 0.002682   0.245  0.864
## Residuals   28 0.30595 0.010927
\end{verbatim}

Thus, the ANOVA table is: Source d.f. SS MS Treatment 3 0.00805 0.002682
Error 28 0.30595 0.010927 Total 31 0.314

\hypertarget{b}{%
\subsubsection{(b)}\label{b}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{qf}\NormalTok{(}\FloatTok{0.95}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{28}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.946685
\end{verbatim}

\hypertarget{c}{%
\subsubsection{(c)}\label{c}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tmp }\OtherTok{\textless{}{-}} \FunctionTok{model.tables}\NormalTok{(but.aov, }\AttributeTok{type=}\StringTok{"means"}\NormalTok{)}
\NormalTok{but.tab }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\FunctionTok{names}\NormalTok{(tmp}\SpecialCharTok{$}\NormalTok{tables[[}\DecValTok{2}\NormalTok{]]), }\FunctionTok{c}\NormalTok{(tmp}\SpecialCharTok{$}\NormalTok{tables[[}\DecValTok{2}\NormalTok{]]), tmp}\SpecialCharTok{$}\NormalTok{n[[}\DecValTok{1}\NormalTok{]])}
\FunctionTok{colnames}\NormalTok{(but.tab) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{names}\NormalTok{(tmp}\SpecialCharTok{$}\NormalTok{tables[}\DecValTok{2}\NormalTok{]), }\StringTok{"means"}\NormalTok{, }\StringTok{"ni"}\NormalTok{)}

\NormalTok{but.tab}\SpecialCharTok{$}\NormalTok{var }\OtherTok{\textless{}{-}} \FunctionTok{sum}\NormalTok{(but.aov}\SpecialCharTok{$}\NormalTok{res}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}\SpecialCharTok{/}\NormalTok{but.aov}\SpecialCharTok{$}\NormalTok{df.residual}\SpecialCharTok{*}\DecValTok{1}\SpecialCharTok{/}\FunctionTok{c}\NormalTok{(tmp}\SpecialCharTok{$}\NormalTok{n[[}\DecValTok{1}\NormalTok{]])}
\NormalTok{but.tab}\SpecialCharTok{$}\NormalTok{sd }\OtherTok{\textless{}{-}} \FunctionTok{sqrt}\NormalTok{(but.tab}\SpecialCharTok{$}\NormalTok{var)}

\NormalTok{but.tab}\SpecialCharTok{$}\NormalTok{lower95 }\OtherTok{\textless{}{-}}\NormalTok{ but.tab}\SpecialCharTok{$}\NormalTok{means}\SpecialCharTok{{-}}\FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, but.aov}\SpecialCharTok{$}\NormalTok{df.residual) }\SpecialCharTok{*}\NormalTok{ but.tab}\SpecialCharTok{$}\NormalTok{sd}
\NormalTok{but.tab}\SpecialCharTok{$}\NormalTok{upper95 }\OtherTok{\textless{}{-}}\NormalTok{ but.tab}\SpecialCharTok{$}\NormalTok{means}\SpecialCharTok{+}\FunctionTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, but.aov}\SpecialCharTok{$}\NormalTok{df.residual) }\SpecialCharTok{*}\NormalTok{ but.tab}\SpecialCharTok{$}\NormalTok{sd}
\NormalTok{but.tab}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   pushes_num    means ni         var         sd  lower95  upper95
## 0          0 38.20714  7 0.001560984 0.03950929 38.12621 38.28807
## 1          1 38.17100 10 0.001092689 0.03305584 38.10329 38.23871
## 2          2 38.19400 10 0.001092689 0.03305584 38.12629 38.26171
## 3          3 38.21200  5 0.002185378 0.04674802 38.11624 38.30776
\end{verbatim}

Thus, the mean waiting time after pushing the button once is 38.171. The
corresponding 95\% CI for this estimate is {[}38.10329, 38.23871{]}. The
mean waiting time after pushing the button three times is 38.212. The
corresponding 95\% CI for this estimate is {[}38.11624, 38.30776{]}.

\hypertarget{d}{%
\subsubsection{(d)}\label{d}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{TukeyHSD}\NormalTok{(but.aov)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = wait_time ~ pushes_num, data = but.dat)
## 
## $pushes_num
##             diff        lwr       upr     p adj
## 1-0 -0.036142857 -0.1767916 0.1045059 0.8955744
## 2-0 -0.013142857 -0.1537916 0.1275059 0.9940396
## 3-0  0.004857143 -0.1622585 0.1719728 0.9998162
## 2-1  0.023000000 -0.1046367 0.1506367 0.9602303
## 3-1  0.041000000 -0.1153224 0.1973224 0.8898585
## 3-2  0.018000000 -0.1383224 0.1743224 0.9890012
\end{verbatim}

Based on the output, we find that the pairwise comparison between the
two mean waiting times of part (c) is 0.041, the number in the fifth row
of the first column called diff. The corresponding 95\% CI is
{[}-0.1153224, 0.1973224{]}. Since the 95\% CI contains 0, we conclude
that the number of pushes of 1 or 3 of the pedestrian button has no
effect on the waiting time for the walk signal.

\hypertarget{e}{%
\subsubsection{(e)}\label{e}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{MSE }\OtherTok{\textless{}{-}} \FloatTok{0.010927}
\NormalTok{L\_hat }\OtherTok{\textless{}{-}}\NormalTok{ (but.tab}\SpecialCharTok{$}\NormalTok{means[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{{-}}\NormalTok{ (but.tab}\SpecialCharTok{$}\NormalTok{means[}\DecValTok{2}\NormalTok{]}\SpecialCharTok{+}\NormalTok{but.tab}\SpecialCharTok{$}\NormalTok{means[}\DecValTok{3}\NormalTok{]}\SpecialCharTok{+}\NormalTok{but.tab}\SpecialCharTok{$}\NormalTok{means[}\DecValTok{4}\NormalTok{])}\SpecialCharTok{/}\DecValTok{3}\NormalTok{)}
\NormalTok{var }\OtherTok{\textless{}{-}}\NormalTok{ MSE}\SpecialCharTok{*}\NormalTok{(}\DecValTok{1}\SpecialCharTok{/}\DecValTok{7}\SpecialCharTok{+}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{1}\SpecialCharTok{/}\DecValTok{3}\NormalTok{)}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\DecValTok{10}\SpecialCharTok{+}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{1}\SpecialCharTok{/}\DecValTok{3}\NormalTok{)}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\DecValTok{10}\SpecialCharTok{+}\NormalTok{(}\SpecialCharTok{{-}}\DecValTok{1}\SpecialCharTok{/}\DecValTok{3}\NormalTok{)}\SpecialCharTok{\^{}}\DecValTok{2}\SpecialCharTok{/}\DecValTok{5}\NormalTok{)}
\NormalTok{t }\OtherTok{\textless{}{-}} \FunctionTok{qt}\NormalTok{(}\FloatTok{0.95}\NormalTok{, }\DecValTok{28}\NormalTok{)}
\NormalTok{lwr }\OtherTok{\textless{}{-}}\NormalTok{ L\_hat }\SpecialCharTok{{-}}\NormalTok{ t}\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(var)}
\NormalTok{upr }\OtherTok{\textless{}{-}}\NormalTok{ L\_hat }\SpecialCharTok{+}\NormalTok{ t}\SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(var)}
\NormalTok{L\_hat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.01480952
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lwr}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.06214939
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{upr}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.09176844
\end{verbatim}

The estimate of contrast is 0.01480952. The corresponding 95\% CI is
{[}-0.06214939, 0.09176844{]}. Since this CI contains 0, we conclude
that the effect of no pushes or pushing the button once on the waiting
time for the walk signal has no difference.

\end{document}
